// Code generated by MockGen. DO NOT EDIT.
// Source: oauth_handler.go
//
// Generated by this command:
//
//	mockgen -source=oauth_handler.go -destination=oauth_handler_mock_test.go -package=handlers_test -typed=true
//

// Package handlers_test is a generated GoMock package.
package handlers_test

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockuserAuthenticator is a mock of userAuthenticator interface.
type MockuserAuthenticator struct {
	ctrl     *gomock.Controller
	recorder *MockuserAuthenticatorMockRecorder
	isgomock struct{}
}

// MockuserAuthenticatorMockRecorder is the mock recorder for MockuserAuthenticator.
type MockuserAuthenticatorMockRecorder struct {
	mock *MockuserAuthenticator
}

// NewMockuserAuthenticator creates a new mock instance.
func NewMockuserAuthenticator(ctrl *gomock.Controller) *MockuserAuthenticator {
	mock := &MockuserAuthenticator{ctrl: ctrl}
	mock.recorder = &MockuserAuthenticatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserAuthenticator) EXPECT() *MockuserAuthenticatorMockRecorder {
	return m.recorder
}

// GoogleOAuth mocks base method.
func (m *MockuserAuthenticator) GoogleOAuth(ctx context.Context, token string) (string, string, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GoogleOAuth", ctx, token)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(int64)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// GoogleOAuth indicates an expected call of GoogleOAuth.
func (mr *MockuserAuthenticatorMockRecorder) GoogleOAuth(ctx, token any) *MockuserAuthenticatorGoogleOAuthCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GoogleOAuth", reflect.TypeOf((*MockuserAuthenticator)(nil).GoogleOAuth), ctx, token)
	return &MockuserAuthenticatorGoogleOAuthCall{Call: call}
}

// MockuserAuthenticatorGoogleOAuthCall wrap *gomock.Call
type MockuserAuthenticatorGoogleOAuthCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockuserAuthenticatorGoogleOAuthCall) Return(accessToken, refreshToken string, exp int64, err error) *MockuserAuthenticatorGoogleOAuthCall {
	c.Call = c.Call.Return(accessToken, refreshToken, exp, err)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockuserAuthenticatorGoogleOAuthCall) Do(f func(context.Context, string) (string, string, int64, error)) *MockuserAuthenticatorGoogleOAuthCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockuserAuthenticatorGoogleOAuthCall) DoAndReturn(f func(context.Context, string) (string, string, int64, error)) *MockuserAuthenticatorGoogleOAuthCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
