// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=service_mock_test.go -package=post_test -typed=true
//

// Package post_test is a generated GoMock package.
package post_test

import (
	context "context"
	reflect "reflect"

	models "github.com/nix-united/golang-echo-boilerplate/internal/models"
	gomock "go.uber.org/mock/gomock"
)

// MockpostRepository is a mock of postRepository interface.
type MockpostRepository struct {
	ctrl     *gomock.Controller
	recorder *MockpostRepositoryMockRecorder
	isgomock struct{}
}

// MockpostRepositoryMockRecorder is the mock recorder for MockpostRepository.
type MockpostRepositoryMockRecorder struct {
	mock *MockpostRepository
}

// NewMockpostRepository creates a new mock instance.
func NewMockpostRepository(ctrl *gomock.Controller) *MockpostRepository {
	mock := &MockpostRepository{ctrl: ctrl}
	mock.recorder = &MockpostRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpostRepository) EXPECT() *MockpostRepositoryMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockpostRepository) Create(ctx context.Context, post *models.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, post)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockpostRepositoryMockRecorder) Create(ctx, post any) *MockpostRepositoryCreateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockpostRepository)(nil).Create), ctx, post)
	return &MockpostRepositoryCreateCall{Call: call}
}

// MockpostRepositoryCreateCall wrap *gomock.Call
type MockpostRepositoryCreateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostRepositoryCreateCall) Return(arg0 error) *MockpostRepositoryCreateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpostRepositoryCreateCall) Do(f func(context.Context, *models.Post) error) *MockpostRepositoryCreateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostRepositoryCreateCall) DoAndReturn(f func(context.Context, *models.Post) error) *MockpostRepositoryCreateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Delete mocks base method.
func (m *MockpostRepository) Delete(ctx context.Context, post *models.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, post)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockpostRepositoryMockRecorder) Delete(ctx, post any) *MockpostRepositoryDeleteCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockpostRepository)(nil).Delete), ctx, post)
	return &MockpostRepositoryDeleteCall{Call: call}
}

// MockpostRepositoryDeleteCall wrap *gomock.Call
type MockpostRepositoryDeleteCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostRepositoryDeleteCall) Return(arg0 error) *MockpostRepositoryDeleteCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpostRepositoryDeleteCall) Do(f func(context.Context, *models.Post) error) *MockpostRepositoryDeleteCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostRepositoryDeleteCall) DoAndReturn(f func(context.Context, *models.Post) error) *MockpostRepositoryDeleteCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPost mocks base method.
func (m *MockpostRepository) GetPost(ctx context.Context, id uint) (models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPost", ctx, id)
	ret0, _ := ret[0].(models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPost indicates an expected call of GetPost.
func (mr *MockpostRepositoryMockRecorder) GetPost(ctx, id any) *MockpostRepositoryGetPostCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPost", reflect.TypeOf((*MockpostRepository)(nil).GetPost), ctx, id)
	return &MockpostRepositoryGetPostCall{Call: call}
}

// MockpostRepositoryGetPostCall wrap *gomock.Call
type MockpostRepositoryGetPostCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostRepositoryGetPostCall) Return(arg0 models.Post, arg1 error) *MockpostRepositoryGetPostCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpostRepositoryGetPostCall) Do(f func(context.Context, uint) (models.Post, error)) *MockpostRepositoryGetPostCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostRepositoryGetPostCall) DoAndReturn(f func(context.Context, uint) (models.Post, error)) *MockpostRepositoryGetPostCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// GetPosts mocks base method.
func (m *MockpostRepository) GetPosts(ctx context.Context) ([]models.Post, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPosts", ctx)
	ret0, _ := ret[0].([]models.Post)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPosts indicates an expected call of GetPosts.
func (mr *MockpostRepositoryMockRecorder) GetPosts(ctx any) *MockpostRepositoryGetPostsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPosts", reflect.TypeOf((*MockpostRepository)(nil).GetPosts), ctx)
	return &MockpostRepositoryGetPostsCall{Call: call}
}

// MockpostRepositoryGetPostsCall wrap *gomock.Call
type MockpostRepositoryGetPostsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostRepositoryGetPostsCall) Return(arg0 []models.Post, arg1 error) *MockpostRepositoryGetPostsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpostRepositoryGetPostsCall) Do(f func(context.Context) ([]models.Post, error)) *MockpostRepositoryGetPostsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostRepositoryGetPostsCall) DoAndReturn(f func(context.Context) ([]models.Post, error)) *MockpostRepositoryGetPostsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Update mocks base method.
func (m *MockpostRepository) Update(ctx context.Context, post *models.Post) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, post)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockpostRepositoryMockRecorder) Update(ctx, post any) *MockpostRepositoryUpdateCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockpostRepository)(nil).Update), ctx, post)
	return &MockpostRepositoryUpdateCall{Call: call}
}

// MockpostRepositoryUpdateCall wrap *gomock.Call
type MockpostRepositoryUpdateCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockpostRepositoryUpdateCall) Return(arg0 error) *MockpostRepositoryUpdateCall {
	c.Call = c.Call.Return(arg0)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockpostRepositoryUpdateCall) Do(f func(context.Context, *models.Post) error) *MockpostRepositoryUpdateCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockpostRepositoryUpdateCall) DoAndReturn(f func(context.Context, *models.Post) error) *MockpostRepositoryUpdateCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
